---
workspace:
  base: /go
  path: src/github.com/${DRONE_REPO}

pipeline:
  test:
    image: golang:1.8
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - mkdir -p /go/bin
      - "curl -s https://glide.sh/get | sh"
      - glide install
      # We have some patched files to use this successfully - until PR's in
      - git checkout vendor/k8s.io/kubernetes/cmd/kubeadm
      - go get -u github.com/golang/lint/golint
      - golint $(go list ./... | grep -v /vendor | grep -v /mocks)
      - go vet $(go list ./... | grep -v /vendor)
      - go get github.com/vektra/mockery/.../
      # We need kubeadm and docker for integration tests
      - "echo ${PWD} ; ls ./bin/docker_downloads.sh ; true"
      - "cd /go/src/github.com/UKHomeOffice/keto-k8 && ./bin/docker_downloads.sh"
      - "curl -sSL https://get.docker.com/builds/Linux/x86_64/docker-1.12.6.tgz > docker.tgz"
      - tar -xzf docker.tgz
      - mv ./docker/docker /usr/local/sbin/
      - go generate $(go list ./... | grep -v /vendor)
      - go test -cover $(go list ./... | grep -v /vendor)
      - go build $(go list ./... | grep -v /vendor)
      - CGO_ENABLED=0 go build -a -v github.com/${DRONE_REPO}/cmd/kmm

  docker_build:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker build -t image .

  docker_int_test:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      # TODO: wire up the scripts in the ./tests directory
      - docker run -i image --help

  image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_keto_k8" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/keto-k8:${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/keto-k8:${DRONE_COMMIT_SHA}
    when:
      event: push

  tag_image_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_keto_k8" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/keto-k8:${DRONE_TAG}
      - docker push quay.io/ukhomeofficedigital/keto-k8:${DRONE_TAG}
    when:
      event: tag

  update_latest_to_quay:
    image: docker:1.12
    environment:
      - DOCKER_HOST=tcp://127.0.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+drone_keto_k8" -p=${DOCKER_PASSWORD} quay.io
      - docker tag image quay.io/ukhomeofficedigital/keto-k8:latest
      - docker push quay.io/ukhomeofficedigital/keto-k8:latest
    when:
      event: push
      branch: master

services:
  dind:
    image: docker:1.12-dind
    privileged: true
    command:
      - "-s"
      - "overlay"